# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44a9d131709e08b2eae574991fe021b679375cf3373a74ec5f9e17919adf94dcea0edc396442ad390e8dd7ddfab3054e82ebecf43d9d101fe90a31da5dff880c

test:
  secret_key_base: 364d0404ac64077534a848de3c91ec4af8ef1672e089e3f7da5c3f80ad069b4c8f37d405fb5d9a29bcbd4aa76fb1a51acb8bc6567e1bc7056b6b80a0c8afe685

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
